### ISSUE TITLE
JBrowse Gene glyph is invisible

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#10]
label for gene appears, but floats near an apparent void.

**Comment by sammyjava** [comment]
In the WTF department, genes have now returned to showing the black mRNA arrows. I've got to look back at my emails because Vivek has explained this to me at least two times. I think I have to hack the track-generating code somehow.

**Comment by sammyjava** [comment]
@vivekkrish could you remind me what's going on here? I've got it buried in email and it would be helpful to have the explanation up on GitHub.

The issue is that my genes are showing as mRNA tracks while exons look perfectly fine. I can't figure out what's different about the gene tracks looking at the JSON with the tool within JBrowse. The blue annotation seems to be working fine, though. Here's an example:

https://mines.legumeinfo.org/legumemine/report.do?id=8909550

**Comment by sammyjava** [comment]
Duplicate issue.
